### ISSUE TITLE
Discovery Manager cannot discover roku stick

### ISSUE THREAD

**Issue by kushG** [ConnectSDK/Web-App-Sampler-Android#1]
I tried the Simple-share-sampler-Android repo & was able to connect to Roku stick. But when I tried doing the same with this repo I could not. So, I tried removing the capability filter from discovery manager, i.e. , I commented out <code>DiscoveryManager.getInstance().setCapabilityFilters(webAppFilter)</code> from the code & was able to discover Roku stick. 
Do I need to configure anything else to run web app? For testing purpose I have added YouTube appId , i.e. , 
<code>  if (device.getServiceByName(RokuService.ID) != null)
                webAppId = "837";
</code> 
to the code but still cannot discover the Roku stick

**Comment by oleksii-frolov** [comment]
This ia a demo for launching Web App and it filters devices by this capability. Roku doesn't support web app launching that's why you don't see it. Of course you can discover Roku if you remove the filter but you can not launch web app on Roku. Please use `ConnectableDevice#hasCapability` method for checking capabilities.

**Comment by kushG** [comment]
Thank you !
